name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup PNPM 8.7.4
        uses: pnpm/action-setup@v2
        with:
          version: 8.7.4

      - name: Setup Node.js for PNPM
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint and Build
        run: pnpm run lint && pnpm run build
